biooo-test/routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['localize'])->group(function () {
//Route::middleware([])->group(function () {
    Route::get('/', function () {
        return view('/welcome');
    });
    Route::get('/dashboard', function () {
        return view('/dashboard');
    })->name('dashboard');

    Route::resource('/locales', \App\Http\Controllers\LocaleController::class);
    Route::get('/setlocale/{locale}', [\App\Http\Controllers\LocaleController::class, 'setLocale'])->name('set.locale');
    Route::resource('/countries', \App\Http\Controllers\CountryController::class);
    Route::resource('/products', \App\Http\Controllers\ProductController::class);
    Route::resource('/vats', \App\Http\Controllers\VatController::class);
});
require __DIR__ . '/auth.php';

biooo-test/app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $fillable = ['country',];

    public function locales(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Locale::class);
    }
}

biooo-test/app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCountryRequest;
use App\Http\Requests\UpdateCountryRequest;
use App\Models\Country;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
//        dd(Country::with('locales')->get());
        return view('countries.countries')->with(['countries' =>  Country::with('locales')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCountryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCountryRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function show(Country $country)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateCountryRequest  $request
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCountryRequest $request, Country $country)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function destroy(Country $country)
    {
        //
    }
}

biooo-test/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

biooo-test/resources/views/countries/add-country.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add Locale') }}
        </h2>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-2 bg-white border-b border-gray-200" style="width:40%;">
{{--                    <x-auth-validation-errors class="mb-4" :errors="$errors" />--}}
                    <form action="{{route('locales.store')}}" method="post" class="flex flex-col">
                        @csrf
                        <input type="text" class="mt-6" name="locale" placeholder="Enter Locale Name" value="{{old('locale')}}" required autofocus>
                        <div class="text-sm text-purple-800">@error('locale'){{$message}}@enderror</div>

                        <input type="text" class="mt-6" name="native" placeholder="Enter Native Locale Name" value="{{old('native')}}" required>
                        <div class="text-sm text-purple-800">@error('native'){{$message}}@enderror</div>

                        <input type="text" class="mt-6" name="iso" placeholder="Enter Locale ISO Code" value="{{old('iso')}}" maxlength="2" required>
                        <div class="text-sm text-purple-800">@error('iso'){{$message}}@enderror</div>
                        <input type="submit" class="mt-6 py-6">
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

biooo-test/resources/views/countries/countries.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Countries') }} <span class="ml-4"><x-nav-link :href="route('countries.create')">{{ __('Add') }} {{ __('country') }}</x-nav-link></span>
        </h2>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-2 bg-white border-b border-gray-200">
                    <table class="table table-auto">
                        <thead>
                        <tr class="table-row table-header-group font-extrabold text-2xl">
                            <td class="table-cell p-3">{{ __('Country') }}</td>
                            <td class="table-cell p-3">{{ __('Language') }}</td>
                            <td class="table-cell p-3">{{ __('VAT') }} {{ __('rate') }}</td>
                            <td class="table-cell p-3">{{ __('Operations') }}</td>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($countries as $country)
                            <tr>
                                <td class=" p-3">{{$country->country}}</td>
                                <td class=" p-3">{{$country->locales[0]->native}}</td>
                                <td class=" p-3">{{$country->iso}}</td>
                                <td class=" p-3 flex place-content-between">
                                    <a href="{{route('countries.edit', ['country' => $country])}}">{{ __('Edit') }}</a>
                                    <a href="{{route('countries.show', ['country' => $country])}}">{{ __('Delete') }}</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

biooo-test/resources/views/countries/delete-country.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add Locale') }}
        </h2>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-2 bg-white border-b border-gray-200" style="width:40%;">
{{--                    <x-auth-validation-errors class="mb-4" :errors="$errors" />--}}
                    <form action="{{route('locales.store')}}" method="post" class="flex flex-col">
                        @csrf
                        <input type="text" class="mt-6" name="locale" placeholder="Enter Locale Name" value="{{old('locale')}}" required autofocus>
                        <div class="text-sm text-purple-800">@error('locale'){{$message}}@enderror</div>

                        <input type="text" class="mt-6" name="native" placeholder="Enter Native Locale Name" value="{{old('native')}}" required>
                        <div class="text-sm text-purple-800">@error('native'){{$message}}@enderror</div>

                        <input type="text" class="mt-6" name="iso" placeholder="Enter Locale ISO Code" value="{{old('iso')}}" maxlength="2" required>
                        <div class="text-sm text-purple-800">@error('iso'){{$message}}@enderror</div>
                        <input type="submit" class="mt-6 py-6">
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

biooo-test/resources/views/countries/edit-country.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Locale') }}
        </h2>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-2 bg-white border-b border-gray-200" style="width:40%;">
                    <form action="{{route('locales.update', ['locale' => $locale->id])}}" method="post" class="flex flex-col">
                        @method('PUT')
                        @csrf
                        <input type="text" class="mt-6" name="locale" placeholder="Enter Locale Name" value="{{$locale->locale}}" required autofocus>
                        <div class="text-sm text-purple-800">@error('locale'){{$message}}@enderror</div>

                        <input type="text" class="mt-6" name="native" placeholder="Enter Native Locale Name" value="{{$locale->native}}" required>
                        <div class="text-sm text-purple-800">@error('native'){{$message}}@enderror</div>

                        <input type="text" class="mt-6" name="iso" placeholder="Enter Locale ISO Code" value="{{$locale->iso}}" maxlength="2" required>
                        <div class="text-sm text-purple-800">@error('iso'){{$message}}@enderror</div>
                        <input type="submit" class="mt-6 py-6">
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

biooo-test/resources/views/countries/show-country.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('You CAN delete Locale ') . $locale->locale }}
        </h2>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-2 bg-white border-b border-gray-200" style="width:40%;">
                    <form action="{{route('locales.destroy', ['locale' => $locale->id])}}" method="post"
                          class="flex flex-col">
                        @csrf
                        @method('delete')
                        <div type="text" class="mt-6">Locale Name: {{$locale->locale}} </div>

                        <div type="text" class="mt-6">Native Locale Name: {{$locale->native}}</div>

                        <div type="text" class="mt-6">Locale ISO Code: {{$locale->iso}}</div>

                        <h2 class="mt-10 font-extrabold text-5xl">Are you sure?</h2>
                        <input type="submit" class="mt-6 py-6" value="SURE!">
                        <input type="button" class="mt-6 py-6" value="Sorry..."
                               onclick="window.location.href='{{route('locales.index')}}'">
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>